image: nice/linkeddata-build
script:
  - ./.drone/build.sh
publish:
  docker:
    imagename: nice/mimir
    username: $$DOCKERHUB_USER
    password: $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    registry_login: true