image: nice/linkeddata-build
script:
  - ./.drone/build.sh
  - ./.drone/stop-docker.sh
deploy:
  docker:
    imagename: nice/mimir
    username: $$DOCKERHUB_USER
    password: $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL