#!/bin/bash
set -exf
freya --output /git/build --compilation "http://schema/ns/compilation" --provenence <(git2prov --path /git --since all --showcontent --showhistory --showcompilation --includeworkingarea)
