#!/bin/bash

freya --output /repo/build --compilation "http://ontologies/compilation" \
  --provenence <(git2prov --path $1 --since all --showcontent --showhistory --showcompilation --includeworkingarea)