#!/bin/bash
mkdir /git/build

while true; do

    inotifywait -m -r -e modify,attrib,close_write,move,create,delete /git/qualitystandards && \
        freya --output /git/build --compilation "http://schema/ns/compilation" --provenence <(git2prov --path /git --since all --showcontent --showhistory --showcompilation --includeworkingarea)

done


